/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jic */

#ifndef _Included_jic
#define _Included_jic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jic
 * Method:    vbenc32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_vbenc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    vbdec32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_vbdec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    vbdenc32
 * Signature: ([II[BI)I
 */
JNIEXPORT jint JNICALL Java_jic_vbdenc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint);

/*
 * Class:     jic
 * Method:    vbddec32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_vbddec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    vbd1enc32
 * Signature: ([II[BI)I
 */
JNIEXPORT jint JNICALL Java_jic_vbd1enc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint);

/*
 * Class:     jic
 * Method:    vbd1dec32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_vbd1dec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    vbzenc32
 * Signature: ([II[BI)I
 */
JNIEXPORT jint JNICALL Java_jic_vbzenc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint);

/*
 * Class:     jic
 * Method:    vbzdec32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_vbzdec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    vsenc32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_vsenc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    vsdec32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_vsdec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nenc32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nenc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4ndec32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ndec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nenc128v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nenc128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4ndec128v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ndec128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nenc256v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nenc256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4ndec256v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ndec256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4ndenc32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ndenc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nddec32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nddec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4ndenc128v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ndenc128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nddec128v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nddec128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4ndenc256v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ndenc256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nddec256v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nddec256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nd1enc32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nd1enc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nd1dec32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nd1dec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nd1enc128v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nd1enc128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nd1dec128v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nd1dec128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nd1enc256v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nd1enc256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nd1dec256v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nd1dec256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nzenc32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nzenc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nzdec32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nzdec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nzenc128v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nzenc128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nzdec128v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nzdec128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4nzenc256v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nzenc256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4nzdec256v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4nzdec256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4enc32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4enc32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4dec32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4dec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4enc128v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4enc128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4dec128v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4dec128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4enc256v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_p4enc256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    p4dec256v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_p4dec256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    p4ddec32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ddec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    p4ddec128v32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ddec128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    p4ddec256v32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_p4ddec256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    p4d1dec32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_p4d1dec32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    p4d1dec128v32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_p4d1dec128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    p4d1dec256v32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_p4d1dec256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    bitnpack32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnpack32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitnunpack32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnunpack32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitnpack128v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnpack128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitnunpack128v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnunpack128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitnpack256v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnpack256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitnunpack256v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnunpack256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitndpack32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitndpack32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitndunpack32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitndunpack32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitndpack128v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitndpack128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitndunpack128v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitndunpack128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitndpack256v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitndpack256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitndunpack256v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitndunpack256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitnd1pack32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnd1pack32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitnd1unpack32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnd1unpack32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitnd1pack128v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnd1pack128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitnd1unpack128v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnd1unpack128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitnd1pack256v32
 * Signature: ([II[B)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnd1pack256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray);

/*
 * Class:     jic
 * Method:    bitnd1unpack256v32
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_jic_bitnd1unpack256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray);

/*
 * Class:     jic
 * Method:    bitpack32
 * Signature: ([II[BI)I
 */
JNIEXPORT jint JNICALL Java_jic_bitpack32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint);

/*
 * Class:     jic
 * Method:    bitunpack32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_bitunpack32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    bitpack128v32
 * Signature: ([II[BI)I
 */
JNIEXPORT jint JNICALL Java_jic_bitpack128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint);

/*
 * Class:     jic
 * Method:    bitunpack128v32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_bitunpack128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    bitpack256v32
 * Signature: ([II[BI)I
 */
JNIEXPORT jint JNICALL Java_jic_bitpack256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint);

/*
 * Class:     jic
 * Method:    bitunpack256v32
 * Signature: ([BI[II)I
 */
JNIEXPORT jint JNICALL Java_jic_bitunpack256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint);

/*
 * Class:     jic
 * Method:    bitdpack32
 * Signature: ([II[BII)I
 */
JNIEXPORT jint JNICALL Java_jic_bitdpack32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitdunpack32
 * Signature: ([BI[III)I
 */
JNIEXPORT jint JNICALL Java_jic_bitdunpack32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitdpack128v32
 * Signature: ([II[BII)I
 */
JNIEXPORT jint JNICALL Java_jic_bitdpack128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitdunpack128v32
 * Signature: ([BI[III)I
 */
JNIEXPORT jint JNICALL Java_jic_bitdunpack128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitdpack256v32
 * Signature: ([II[BII)I
 */
JNIEXPORT jint JNICALL Java_jic_bitdpack256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitdunpack256v32
 * Signature: ([BI[III)I
 */
JNIEXPORT jint JNICALL Java_jic_bitdunpack256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitd1pack32
 * Signature: ([II[BII)I
 */
JNIEXPORT jint JNICALL Java_jic_bitd1pack32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitd1unpack32
 * Signature: ([BI[III)I
 */
JNIEXPORT jint JNICALL Java_jic_bitd1unpack32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitd1pack128v32
 * Signature: ([II[BII)I
 */
JNIEXPORT jint JNICALL Java_jic_bitd1pack128v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitd1unpack128v32
 * Signature: ([BI[III)I
 */
JNIEXPORT jint JNICALL Java_jic_bitd1unpack128v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitd1pack256v32
 * Signature: ([II[BII)I
 */
JNIEXPORT jint JNICALL Java_jic_bitd1pack256v32
  (JNIEnv *, jclass, jintArray, jint, jbyteArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitd1unpack256v32
 * Signature: ([BI[III)I
 */
JNIEXPORT jint JNICALL Java_jic_bitd1unpack256v32
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint, jint);

/*
 * Class:     jic
 * Method:    bit32
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_jic_bit32
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     jic
 * Method:    bitd32
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_jic_bitd32
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     jic
 * Method:    bitd132
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_jic_bitd132
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
